### ISSUE TITLE
Python 3.6 compatibility

### ISSUE THREAD

**Issue by danilobellini** [haypo/bytecode#3] opened 2016-10-22 19:22 UTC
I'd like to know if there is any plan to make _bytecode_ compatible with Python 3.6.

The main reason it's important to me is that I'm using this package in my [PyScanPrev](https://github.com/danilobellini/pyscanprev) project.

**Comment by serprex** [comment] 2016-10-23 22:53
I'm going to start on this, @haypo are you wanting the library to dynamically do version detection? Not sure what the version compatibility story is here

**Comment by haypo** [comment] 2016-10-24 17:16
I pushed Serhiy's change: commit 430784c41f2cf3dff584201298f898f69ea38028.

@serprex: "I'm going to start on this, @haypo are you wanting the library to dynamically do version detection? Not sure what the version compatibility story is here"

Serhiy's change uses the version of the running Python. An enhancement would be to have a version argument somewhere.

**Comment by haypo** [comment] 2016-10-25 18:17
Le 24 oct. 2016 00:53, "Demur Rumed" <notifications@github.com> a écrit :
>
> I'm going to start on this, @haypo are you wanting the library to
dynamically do version detection? Not sure what the version compatibility
story is here

A first step would be to use the version of the running python.

**Comment by serprex** [comment] 2016-10-25 18:43
Serhiy's patch lgtm

**Comment by haypo** [comment] 2016-11-18 16:36
It seems like the issue is now fixed, so I close it.

**Closed by haypo** 2016-11-18 16:36 UTC
